name: Continuous Integration

on:
  pull_request_target:
    branches:
      - master
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Format
        run: echo "Continuous Integration"
      - name: Branch
        run: echo ${{github.ref}}